export const INIT_BOARD = "INIT_BOARD"
export const SET_TILES = "SET_TILES"
export const LOCK_BOARD = "LOCK_BOARD"
export const INCREMENT_SCORE = "INCREMENT_SCORE"
export const NEXT_LEVEL = "NEXT_LEVEL"
