export const MOBILE_BREAK_POINT_NUM = 600;
export const MOBILE_BREAK_POINT = `${MOBILE_BREAK_POINT_NUM}px`;
export const TABLET_BREAK_POINT = "1024px";
export const TABLET_CONDITION = `(max-width: ${TABLET_BREAK_POINT}) and (min-width: ${MOBILE_BREAK_POINT})`;
export const LARGE_SCREEN_BREAK_POINT = "1900px";
export const NORMAL_SCREEN_WIDTH = "90vw";
export const LARGE_SCREEN_WIDTH = "1670px";
export const PURPLE = "#604cd5";
export const LIGHT_GREY = "#e0e0e0";